### ISSUE TITLE
An unhandled exception occurred

### ISSUE THREAD

**Issue by xelr233** [imDema/FreeMove#31]
System: Windows 11 22H2
Version: 2.99.0
![image](https://github.com/user-attachments/assets/49e2ac79-c8af-41bd-90c8-6c001f0a3f58)

************** 异常文本 **************
System.ArgumentException: The path is empty. (Parameter 'path')
   at System.IO.Path.GetFullPath(String path)
   at System.Diagnostics.FileVersionInfo.GetVersionInfo(String fileName)
   at FreeMove.Updater..ctor(Boolean Silent)
   at FreeMove.Updater.SilentCheck()
   at FreeMove.Form1.Form1_Load(Object sender, EventArgs e)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)

************** 已加载的程序集 **************
System.Private.CoreLib
    程序集版本:6.0.0.0
    Win32 版本:6.0.3624.51421
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.36/System.Private.CoreLib.dll
----------------------------------------
FreeMove
    程序集版本:2.99.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Runtime
    程序集版本:6.0.0.0
    Win32 版本:6.0.3624.51421
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.36/System.Runtime.dll
----------------------------------------
System.Windows.Forms
    程序集版本:6.0.2.0
    Win32 版本:6.0.3624.51513
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.36/System.Windows.Forms.dll
----------------------------------------
System.Windows.Forms.Primitives
    程序集版本:6.0.2.0
    Win32 版本:6.0.3624.51513
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.36/System.Windows.Forms.Primitives.dll
----------------------------------------
System.ComponentModel.Primitives
    程序集版本:6.0.0.0
    Win32 版本:6.0.3624.51421
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.36/System.ComponentModel.Primitives.dll
----------------------------------------
System.Runtime.InteropServices
    程序集版本:6.0.0.0
    Win32 版本:6.0.3624.51421
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.36/System.Runtime.InteropServices.dll
----------------------------------------
System.Drawing.Primitives
    程序集版本:6.0.0.0
    Win32 版本:6.0.3624.51421
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.36/System.Drawing.Primitives.dll
----------------------------------------
System.Collections.Specialized
    程序集版本:6.0.0.0
    Win32 版本:6.0.3624.51421
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.36/System.Collections.Specialized.dll
----------------------------------------
System.Threading
    程序集版本:6.0.0.0
    Win32 版本:6.0.3624.51421
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.36/System.Threading.dll
----------------------------------------
System.Drawing.Common
    程序集版本:7.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Diagnostics.TraceSource
    程序集版本:6.0.0.0
    Win32 版本:6.0.3624.51421
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.36/System.Diagnostics.TraceSource.dll
----------------------------------------
System.Collections
    程序集版本:6.0.0.0
    Win32 版本:6.0.3624.51421
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.36/System.Collections.dll
----------------------------------------
Microsoft.Win32.Primitives
    程序集版本:6.0.0.0
    Win32 版本:6.0.3624.51421
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.36/Microsoft.Win32.Primitives.dll
----------------------------------------
System.ComponentModel.EventBasedAsync
    程序集版本:6.0.0.0
    Win32 版本:6.0.3624.51421
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.36/System.ComponentModel.EventBasedAsync.dll
----------------------------------------
System.Threading.Thread
    程序集版本:6.0.0.0
    Win32 版本:6.0.3624.51421
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.36/System.Threading.Thread.dll
----------------------------------------
Accessibility
    程序集版本:4.0.0.0
    Win32 版本:6.0.3624.51513
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.36/Accessibility.dll
----------------------------------------
System.ComponentModel.TypeConverter
    程序集版本:6.0.0.0
    Win32 版本:6.0.3624.51421
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.36/System.ComponentModel.TypeConverter.dll
----------------------------------------
System.Memory
    程序集版本:6.0.0.0
    Win32 版本:6.0.3624.51421
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.36/System.Memory.dll
----------------------------------------
System.Runtime.CompilerServices.Unsafe
    程序集版本:6.0.0.0
    Win32 版本:6.0.3624.51421
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.36/System.Runtime.CompilerServices.Unsafe.dll
----------------------------------------
System.Numerics.Vectors
    程序集版本:6.0.0.0
    Win32 版本:6.0.3624.51421
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.36/System.Numerics.Vectors.dll
----------------------------------------
Microsoft.Win32.SystemEvents
    程序集版本:7.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Collections.Concurrent
    程序集版本:6.0.0.0
    Win32 版本:6.0.3624.51421
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.36/System.Collections.Concurrent.dll
----------------------------------------
System.ComponentModel
    程序集版本:6.0.0.0
    Win32 版本:6.0.3624.51421
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.36/System.ComponentModel.dll
----------------------------------------
System.Resources.Extensions
    程序集版本:6.0.0.0
    Win32 版本:6.0.3624.51421
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.36/System.Resources.Extensions.dll
----------------------------------------
System.Drawing
    程序集版本:6.0.2.0
    Win32 版本:6.0.3624.51513
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.36/System.Drawing.dll
----------------------------------------
System.ObjectModel
    程序集版本:6.0.0.0
    Win32 版本:6.0.3624.51421
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.36/System.ObjectModel.dll
----------------------------------------
System.Linq
    程序集版本:6.0.0.0
    Win32 版本:6.0.3624.51421
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.36/System.Linq.dll
----------------------------------------
System.Collections.NonGeneric
    程序集版本:6.0.0.0
    Win32 版本:6.0.3624.51421
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.36/System.Collections.NonGeneric.dll
----------------------------------------
System.Xml.XmlSerializer
    程序集版本:6.0.0.0
    Win32 版本:6.0.3624.51421
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.36/System.Xml.XmlSerializer.dll
----------------------------------------
System.Private.Xml
    程序集版本:6.0.0.0
    Win32 版本:6.0.3624.51421
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.36/System.Private.Xml.dll
----------------------------------------
System.Net.Requests
    程序集版本:6.0.0.0
    Win32 版本:6.0.3624.51421
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.36/System.Net.Requests.dll
----------------------------------------
System.Diagnostics.FileVersionInfo
    程序集版本:6.0.0.0
    Win32 版本:6.0.3624.51421
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.36/System.Diagnostics.FileVersionInfo.dll
----------------------------------------
System.Threading.ThreadPool
    程序集版本:6.0.0.0
    Win32 版本:6.0.3624.51421
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.36/System.Threading.ThreadPool.dll
----------------------------------------
System.Private.Uri
    程序集版本:6.0.0.0
    Win32 版本:6.0.3624.51421
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.36/System.Private.Uri.dll
----------------------------------------
System.Runtime.Loader
    程序集版本:6.0.0.0
    Win32 版本:6.0.3624.51421
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.36/System.Runtime.Loader.dll
----------------------------------------
System.Windows.Forms.resources
    程序集版本:6.0.2.0
    Win32 版本:6.0.3624.51513
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.36/zh-Hans/System.Windows.Forms.resources.dll
----------------------------------------
System.Diagnostics.StackTrace
    程序集版本:6.0.0.0
    Win32 版本:6.0.3624.51421
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.36/System.Diagnostics.StackTrace.dll
----------------------------------------
System.Reflection.Metadata
    程序集版本:6.0.0.0
    Win32 版本:6.0.3624.51421
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.36/System.Reflection.Metadata.dll
----------------------------------------
System.Collections.Immutable
    程序集版本:6.0.0.0
    Win32 版本:6.0.3624.51421
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.36/System.Collections.Immutable.dll
----------------------------------------

************** JIT 调试 **************

**Comment by xelr233** [comment]
## 分析

这个 bug 在 `Updater` 构造函数中调用 `FileVersionInfo.GetVersionInfo` 时，传入的文件路径为空字符串。

从调用链来看：
```
Form1.Load → Updater.SilentCheck() → Updater..ctor(true) → FileVersionInfo.GetVersionInfo("")
```

常见触发场景：
1. 程序通过 **dotnet publish 单文件发布** 或 **ReadyToRun** 部署时，`Assembly.Location` 可能返回空字符串
2. 某些杀毒软件或系统策略清空了 PE 文件的版本信息查询路径
3. 在 Windows 11 22H2 + .NET 6.0.36 环境下，单文件部署场景更常见

## 建议修复

```csharp
// Updater.cs - 构造函数中加空路径检查
public Updater(bool Silent)
{
    string assemblyPath = Assembly.GetExecutingAssembly().Location;
    
    // 防御性检查：单文件部署时 Location 可能为空
    if (string.IsNullOrEmpty(assemblyPath))
    {
        // 回退到 Process 模块路径或 AppContext.BaseDirectory
        assemblyPath = Environment.ProcessPath 
            ?? Path.Combine(AppContext.BaseDirectory, "FreeMove.exe");
    }

    if (!string.IsNullOrEmpty(assemblyPath) && File.Exists(assemblyPath))
    {
        var versionInfo = FileVersionInfo.GetVersionInfo(assemblyPath);
        // ... 原有逻辑
    }
}
```

## 复现环境确认

能否确认一下：
- 是通过 **安装包** 安装的，还是 **便携版/单文件版**？
- 这个问题是否在每次启动时都会触发，还是偶发？

这样我可以更精确地定位 root cause 并提交 PR。
